import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray,
    backgroundColor: COLORS.white,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.gray,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: COLORS.black,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  comboTitleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  comboTitle: {
    fontSize: 20,
    fontWeight: "bold",
    flex: 1,
    marginRight: 8,
    lineHeight: 28,
  },
  detailButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailText: {
    fontSize: 15,
    color: COLORS.primary,
    fontWeight: "bold",
  },
  sectionBox: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    backgroundColor: COLORS.white,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 16,
  },
  serviceStatusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  serviceStatusText: {
    fontSize: 16,
    color: '#666',
  },
  dateRangeButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateRangeText: {
    fontSize: 16,
    color: '#666',
    marginRight: 4,
  },
  dateSelectorScrollView: {},
  dateButton: {
    backgroundColor: '#F0F0F0',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginRight: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  dateButtonSelected: {
    backgroundColor: COLORS.white,
    borderColor: '#FF7F50',
    borderWidth: 1.5,
  },
  dateButtonText: {
    fontSize: 15,
    color: COLORS.black,
    fontWeight: '500',
  },
  dateButtonTextSelected: {
    color: '#FF7F50',
    fontWeight: 'bold',
  },
  dateButtonDisabled: {
    backgroundColor: '#F0F0F0',
    paddingHorizontal: 16,
  },
  badgesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  badge: {
    borderWidth: 1,
    borderColor: COLORS.gray,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: COLORS.white,
  },
  badgeText: {
    fontSize: 12,
    color: '#555',
  },
  divider: {
    height: 1,
    backgroundColor: '#EFEFEF',
    marginVertical: 16,
  },
  quantityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  quantityLabel: {
    fontSize: 16,
    color: COLORS.black,
    flex: 1,
  },
  priceText: {
    fontSize: 14,
    color: COLORS.black,
    width: 100,
    textAlign: "right",
    marginRight: 16,
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  quantityButton: {
    padding: 4,
  },
  quantityValue: {
    fontSize: 18,
    fontWeight: "bold",
    marginHorizontal: 16,
    minWidth: 24,
    textAlign: "center",
  },
  optionItem: {
    backgroundColor: '#FAFAFA',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EEE',
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: COLORS.black,
    marginBottom: 4,
  },
  optionDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  optionPrice: {
    fontSize: 14,
    fontWeight: "bold",
    color: COLORS.primary,
    textAlign: "right",
  },
  discountText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'green',
  },
  // --- FOOTER STYLES  ---
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: COLORS.gray,
    backgroundColor: COLORS.white,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
  },
  footerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  totalPriceLabel: {
    fontSize: 16,
    color: '#666',
  },
  totalPrice: {
    fontSize: 22,
    fontWeight: "bold",
    color: COLORS.primary,
  },
  footerButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addToCartButton: {
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderRadius: 28,
    marginRight: 12,
  },
  bookNowButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: 'center',
  },
  bookNowButtonText: {
    color: COLORS.white,
    fontWeight: "bold",
    fontSize: 16,
  },
});